// Code generated by protoc-gen-micro. DO NOT EDIT.
// source: proto/micro-helloworld/micro-helloworld.proto

package go_micro_service_microhelloworld

import (
	fmt "fmt"
	proto "github.com/golang/protobuf/proto"
	math "math"
)

import (
	context "context"
	api "github.com/micro/go-micro/v2/api"
	client "github.com/micro/go-micro/v2/client"
	server "github.com/micro/go-micro/v2/server"
)

// Reference imports to suppress errors if they are not otherwise used.
var _ = proto.Marshal
var _ = fmt.Errorf
var _ = math.Inf

// This is a compile-time assertion to ensure that this generated file
// is compatible with the proto package it is being compiled against.
// A compilation error at this line likely means your copy of the
// proto package needs to be updated.
const _ = proto.ProtoPackageIsVersion3 // please upgrade the proto package

// Reference imports to suppress errors if they are not otherwise used.
var _ api.Endpoint
var _ context.Context
var _ client.Option
var _ server.Option

// Api Endpoints for MicroHelloworld service

func NewMicroHelloworldEndpoints() []*api.Endpoint {
	return []*api.Endpoint{}
}

// Client API for MicroHelloworld service

type MicroHelloworldService interface {
	Call(ctx context.Context, in *Request, opts ...client.CallOption) (*Response, error)
	Stream(ctx context.Context, in *StreamingRequest, opts ...client.CallOption) (MicroHelloworld_StreamService, error)
	PingPong(ctx context.Context, opts ...client.CallOption) (MicroHelloworld_PingPongService, error)
}

type microHelloworldService struct {
	c    client.Client
	name string
}

func NewMicroHelloworldService(name string, c client.Client) MicroHelloworldService {
	return &microHelloworldService{
		c:    c,
		name: name,
	}
}

func (c *microHelloworldService) Call(ctx context.Context, in *Request, opts ...client.CallOption) (*Response, error) {
	req := c.c.NewRequest(c.name, "MicroHelloworld.Call", in)
	out := new(Response)
	err := c.c.Call(ctx, req, out, opts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

func (c *microHelloworldService) Stream(ctx context.Context, in *StreamingRequest, opts ...client.CallOption) (MicroHelloworld_StreamService, error) {
	req := c.c.NewRequest(c.name, "MicroHelloworld.Stream", &StreamingRequest{})
	stream, err := c.c.Stream(ctx, req, opts...)
	if err != nil {
		return nil, err
	}
	if err := stream.Send(in); err != nil {
		return nil, err
	}
	return &microHelloworldServiceStream{stream}, nil
}

type MicroHelloworld_StreamService interface {
	Context() context.Context
	SendMsg(interface{}) error
	RecvMsg(interface{}) error
	Close() error
	Recv() (*StreamingResponse, error)
}

type microHelloworldServiceStream struct {
	stream client.Stream
}

func (x *microHelloworldServiceStream) Close() error {
	return x.stream.Close()
}

func (x *microHelloworldServiceStream) Context() context.Context {
	return x.stream.Context()
}

func (x *microHelloworldServiceStream) SendMsg(m interface{}) error {
	return x.stream.Send(m)
}

func (x *microHelloworldServiceStream) RecvMsg(m interface{}) error {
	return x.stream.Recv(m)
}

func (x *microHelloworldServiceStream) Recv() (*StreamingResponse, error) {
	m := new(StreamingResponse)
	err := x.stream.Recv(m)
	if err != nil {
		return nil, err
	}
	return m, nil
}

func (c *microHelloworldService) PingPong(ctx context.Context, opts ...client.CallOption) (MicroHelloworld_PingPongService, error) {
	req := c.c.NewRequest(c.name, "MicroHelloworld.PingPong", &Ping{})
	stream, err := c.c.Stream(ctx, req, opts...)
	if err != nil {
		return nil, err
	}
	return &microHelloworldServicePingPong{stream}, nil
}

type MicroHelloworld_PingPongService interface {
	Context() context.Context
	SendMsg(interface{}) error
	RecvMsg(interface{}) error
	Close() error
	Send(*Ping) error
	Recv() (*Pong, error)
}

type microHelloworldServicePingPong struct {
	stream client.Stream
}

func (x *microHelloworldServicePingPong) Close() error {
	return x.stream.Close()
}

func (x *microHelloworldServicePingPong) Context() context.Context {
	return x.stream.Context()
}

func (x *microHelloworldServicePingPong) SendMsg(m interface{}) error {
	return x.stream.Send(m)
}

func (x *microHelloworldServicePingPong) RecvMsg(m interface{}) error {
	return x.stream.Recv(m)
}

func (x *microHelloworldServicePingPong) Send(m *Ping) error {
	return x.stream.Send(m)
}

func (x *microHelloworldServicePingPong) Recv() (*Pong, error) {
	m := new(Pong)
	err := x.stream.Recv(m)
	if err != nil {
		return nil, err
	}
	return m, nil
}

// Server API for MicroHelloworld service

type MicroHelloworldHandler interface {
	Call(context.Context, *Request, *Response) error
	Stream(context.Context, *StreamingRequest, MicroHelloworld_StreamStream) error
	PingPong(context.Context, MicroHelloworld_PingPongStream) error
}

func RegisterMicroHelloworldHandler(s server.Server, hdlr MicroHelloworldHandler, opts ...server.HandlerOption) error {
	type microHelloworld interface {
		Call(ctx context.Context, in *Request, out *Response) error
		Stream(ctx context.Context, stream server.Stream) error
		PingPong(ctx context.Context, stream server.Stream) error
	}
	type MicroHelloworld struct {
		microHelloworld
	}
	h := &microHelloworldHandler{hdlr}
	return s.Handle(s.NewHandler(&MicroHelloworld{h}, opts...))
}

type microHelloworldHandler struct {
	MicroHelloworldHandler
}

func (h *microHelloworldHandler) Call(ctx context.Context, in *Request, out *Response) error {
	return h.MicroHelloworldHandler.Call(ctx, in, out)
}

func (h *microHelloworldHandler) Stream(ctx context.Context, stream server.Stream) error {
	m := new(StreamingRequest)
	if err := stream.Recv(m); err != nil {
		return err
	}
	return h.MicroHelloworldHandler.Stream(ctx, m, &microHelloworldStreamStream{stream})
}

type MicroHelloworld_StreamStream interface {
	Context() context.Context
	SendMsg(interface{}) error
	RecvMsg(interface{}) error
	Close() error
	Send(*StreamingResponse) error
}

type microHelloworldStreamStream struct {
	stream server.Stream
}

func (x *microHelloworldStreamStream) Close() error {
	return x.stream.Close()
}

func (x *microHelloworldStreamStream) Context() context.Context {
	return x.stream.Context()
}

func (x *microHelloworldStreamStream) SendMsg(m interface{}) error {
	return x.stream.Send(m)
}

func (x *microHelloworldStreamStream) RecvMsg(m interface{}) error {
	return x.stream.Recv(m)
}

func (x *microHelloworldStreamStream) Send(m *StreamingResponse) error {
	return x.stream.Send(m)
}

func (h *microHelloworldHandler) PingPong(ctx context.Context, stream server.Stream) error {
	return h.MicroHelloworldHandler.PingPong(ctx, &microHelloworldPingPongStream{stream})
}

type MicroHelloworld_PingPongStream interface {
	Context() context.Context
	SendMsg(interface{}) error
	RecvMsg(interface{}) error
	Close() error
	Send(*Pong) error
	Recv() (*Ping, error)
}

type microHelloworldPingPongStream struct {
	stream server.Stream
}

func (x *microHelloworldPingPongStream) Close() error {
	return x.stream.Close()
}

func (x *microHelloworldPingPongStream) Context() context.Context {
	return x.stream.Context()
}

func (x *microHelloworldPingPongStream) SendMsg(m interface{}) error {
	return x.stream.Send(m)
}

func (x *microHelloworldPingPongStream) RecvMsg(m interface{}) error {
	return x.stream.Recv(m)
}

func (x *microHelloworldPingPongStream) Send(m *Pong) error {
	return x.stream.Send(m)
}

func (x *microHelloworldPingPongStream) Recv() (*Ping, error) {
	m := new(Ping)
	if err := x.stream.Recv(m); err != nil {
		return nil, err
	}
	return m, nil
}
